language: cpp

before_install:
  - pip install --user cpp-coveralls

before_script:
  - mkdir "${TRAVIS_BUILD_DIR}/build"
  - cd "${TRAVIS_BUILD_DIR}/build"
  - cmake ..

script:
  - cd "${TRAVIS_BUILD_DIR}/build"
  - make
  - ctest

after_success:
  - coveralls --root ..

notifications:
  email: false
